---
dist: xenial
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=betacloud/horizon
  matrix:
    - VERSION=victoria SOURCE_REGISTRY=quay.io

script:
  - bash scripts/build.sh

deploy:
  - provider: script
    script: bash scripts/push.sh
    skip_cleanup: true
    on:
      branch: master
